name: seeforme
description: "A vision assistance app that helps users understand their surroundings through image analysis."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  flutter_tts: ^3.8.5
  volume_controller: ^2.0.8
  image: ^4.1.7
  shared_preferences: ^2.2.2
  tflite_flutter: ^0.12.1
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - assets/models/yolov5.tflite
